# Generated by Django 5.0 on 2023-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre_apellido',
            field=models.CharField(max_length=120),
        ),
    ]
